channels:
  - conda-forge

dependencies:
  - python>=3.9
  - scipy
  - pandas
  - numpy
  - numba
  - statsmodels
  - metpy
  - jupyter
  - scikit-learn
  - plotly
  - fluxdataqaqc
  - pingouin
  - sqlalchemy